-- THÔNG BÁO ĐĂNG KÝ HỌC MỚI · REALTIME + WEB PUSH + ZALO
-- Chạy toàn bộ file này một lần trong Supabase SQL Editor.
-- Yêu cầu đã chạy:
--   1) TAO-DANG-KY-HOC-LAI-XE-MOI.sql
--   2) CAP-NHAT-TRUNG-TAM-THONG-BAO-BUOC-11.sql
--   3) CAP-NHAT-THONG-BAO-DAY-BUOC-12.sql

begin;

do $$
begin
  if to_regclass('public.new_student_registrations') is null then
    raise exception 'Cần chạy TAO-DANG-KY-HOC-LAI-XE-MOI.sql trước.';
  end if;
  if to_regclass('public.app_notifications') is null then
    raise exception 'Cần chạy CAP-NHAT-TRUNG-TAM-THONG-BAO-BUOC-11.sql trước.';
  end if;
  if to_regclass('public.app_users') is null then
    raise exception 'Không tìm thấy bảng tài khoản quản lý app_users.';
  end if;
end;
$$;

-- Bảng tín hiệu chỉ chứa thời điểm phát sinh, hoàn toàn không chứa thông tin học viên.
-- Giao diện Admin nghe bảng này bằng Supabase Realtime, sau đó dùng RPC có token Admin
-- để tải dữ liệu đăng ký thật. Vì vậy không phải công khai họ tên hoặc số điện thoại.
create table if not exists public.new_student_registration_signals (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now()
);

alter table public.new_student_registration_signals enable row level security;
revoke all on public.new_student_registration_signals from public;
grant select on public.new_student_registration_signals to anon, authenticated;

drop policy if exists new_student_registration_signals_read on public.new_student_registration_signals;
create policy new_student_registration_signals_read
  on public.new_student_registration_signals
  for select
  to anon, authenticated
  using (true);

-- Thêm bảng tín hiệu vào publication Realtime nếu chưa có.
do $$
begin
  if exists (select 1 from pg_publication where pubname='supabase_realtime')
    and not exists (
      select 1
      from pg_publication_tables
      where pubname='supabase_realtime'
        and schemaname='public'
        and tablename='new_student_registration_signals'
    )
  then
    alter publication supabase_realtime
      add table public.new_student_registration_signals;
  end if;
end;
$$;

-- Nhật ký chống gửi trùng Zalo khi hệ thống có nhiều tài khoản Admin.
create table if not exists public.app_zalo_delivery_log (
  notification_key text primary key,
  registration_id uuid references public.new_student_registrations(id) on delete set null,
  status text not null default 'processing'
    check (status in ('processing','sent','failed')),
  provider_response jsonb,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.app_zalo_delivery_log enable row level security;
revoke all on public.app_zalo_delivery_log from public, anon, authenticated;

create or replace function public.app_new_student_registration_alert()
returns trigger
language plpgsql
security definer
set search_path=public,extensions,pg_temp
as $$
declare
  v_key text := 'new-student-registration:' || new.id;
  v_body text;
begin
  v_body := new.full_name
    || ' · ' || new.license_class
    || ' · ' || new.phone
    || case when coalesce(new.area,'')<>'' then ' · '||new.area else '' end;

  insert into public.app_notifications(
    recipient_kind,
    recipient_id,
    notification_key,
    category,
    tone,
    icon,
    title,
    body,
    href,
    action_label,
    event_at
  )
  select
    'manager',
    manager.id,
    v_key,
    'general',
    'blue',
    '🎓',
    'Có đăng ký học lái xe mới',
    v_body,
    '/?open=new-student&registration=' || new.id,
    'Xem đăng ký',
    new.created_at
  from public.app_users manager
  where manager.active
    and manager.role='admin'
  on conflict(recipient_kind,recipient_id,notification_key) do nothing;

  insert into public.new_student_registration_signals default values;

  -- Bảng tín hiệu chỉ phục vụ sự kiện tức thời, không cần lưu lâu dài.
  delete from public.new_student_registration_signals
  where created_at < now() - interval '2 days';

  return new;
end;
$$;

drop trigger if exists new_student_registration_alert_trigger
  on public.new_student_registrations;

create trigger new_student_registration_alert_trigger
after insert on public.new_student_registrations
for each row execute function public.app_new_student_registration_alert();

select pg_notify('pgrst','reload schema');
commit;

select
  to_regclass('public.new_student_registration_signals') as realtime_signal_table,
  to_regclass('public.app_zalo_delivery_log') as zalo_delivery_log,
  to_regprocedure('public.app_new_student_registration_alert()') as alert_function;
